### ISSUE TITLE
EC2 instance doesn't get stopped after a build failure

### ISSUE THREAD

**Issue by dasiths** [aws-samples/aws-codepipeline-custom-action#3]
We have our build script fail for multiple reasons during development. Our expectation was that the EC2 instance would get deleted after the pipeline completes but they keep running after a build failure.

The output from the step functions is as follows
```
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'Prepare Release Builder Input' (entered at the event id #196). Invalid path '$[0]' : Filter: [0] can only be applied to arrays. Current context is: {params={pipeline={jobId=fcd7db40-6366-41f2-ae83-6289c4602b8f, executionId=624dc6d0-e226-4e55-b047-f8abf520c939, arn=arn:aws:codepipeline:ap-southeast-2:583812563872:SIT12-RnL-Build_pipeline02, name=SIT12}, artifacts={input={bucketName=our-artefactbucket, objectKey=SIT12-RnL-Build_pipe/SourceDock/ugScfFR}, output={path=, bucketName=our-artefactbucket, objectKey=SIT12-RnL-Build_pipe/BuildDocke/amZpHzo}}, instance={imageId=ami-0951414059f50d500, instanceType=t3.2xlarge, keyName=}, command={commandText=.\\build.ps1 Build, workingDirectory=C:\\\\source, timeout=3600}}, status={instance={instanceId=i-0e6811d5f254ee743, status=STARTED}}}"
}
```

It's failing at the `Prepare Release Builder Input` step
![image](https://user-images.githubusercontent.com/16128850/86991938-a8af0200-c1e3-11ea-8e27-4f941ae2b6c6.png)

**Comment by dasiths** [comment]
Any direction here would be highly appreciated @kolomied . 

I'm thinking of changing this
```
            "Prepare Release Builder Input": {
              "Type": "Pass",
              "InputPath": "$[0]",
              "Next": "Release Builder Flow"
            },
```
to this
```
            "Prepare Release Builder Input": {
              "Type": "Pass",
              "InputPath": "$",
              "Next": "Release Builder Flow"
            },
```
in our main cloud formation template.

**Comment by kolomied** [comment]
@dasiths Please take a look - I submitted a PR with simplified state passing between Step Function stages and added a missing lambda that reports job execution status at the end.

**Comment by dasiths** [comment]
Thanks. I will have a look.

**Comment by kolomied** [comment]
@dasiths Going to close this one - feel free to reopen if you face further issues.
